config/routes.rb
Thredded::Application.routes.draw do
  mount_sextant if Rails.env.development?
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  resources :users

  devise_scope :user do
    match '/auth/:provider/callback', to: 'sessions#create'
  end

  get '/auth/failure', to: redirect('/')
  get '/auth/github', as: :auth_github
  put '/identities' => 'identities#update', as: :identity
  post '/mail/receive' => 'griddler/emails#create'

  constraints(SetupThredded.new) do
    root to: 'setups#new'
    get '/:step' => 'setups#new', constraints: { step: /\d{1}/ }, as: :new_setup
    post '/:step' => 'setups#create', constraints: { step: /\d{1}/ }, as: :create_setup
    resource :setup
  end

  resources :preferences

  match '/login' => redirect('/users/sign_in')
  match '/log_in' => redirect('/users/sign_in')
  match '/sign_in' => redirect('/users/sign_in')
  match '/logout' => redirect('/users/sign_out')
  match '/log_out' => redirect('/users/sign_out')
  match '/forgot_password' => redirect('/users/password/new')
  match '/user/forgot_password' => redirect('/users/password/new')
  match '/user/forgot_username' => redirect('/users/password/new')

  constraints(lambda{|req| req.env["QUERY_STRING"].include? 'q=' }) do
    get '/:messageboard_id(.:format)' => 'topics#search', as: :messageboard_search
  end

  get '/:messageboard_id/users' => 'users#index', as: :messageboard_users

  get '/:messageboard_id(.:format)' => 'topics#index', as: :messageboard_topics
  get '/:messageboard_id/topics/new/(:type)' => 'topics#new', as: :new_messageboard_topic
  get '/:messageboard_id/topics/category/:category_id' => 'topics#by_category', as: :messageboard_topics_by_category
  get '/:messageboard_id/:topic_id/edit(.:format)' => 'topics#edit', as: :edit_messageboard_topic
  put '/:messageboard_id/:topic_id(.:format)' => 'topics#update', as: :messageboard_topic
  post '/:messageboard_id/topics(.:format)' => 'topics#create', as: :create_messageboard_topic

  get '/:messageboard_id/private_topics/new/(:type)' => 'private_topics#new', as: :new_messageboard_private_topic
  get '/:messageboard_id/private_topics(.:format)' => 'private_topics#index', as: :messageboard_private_topics
  post '/:messageboard_id/private_topics(.:format)' => 'private_topics#create', as: :create_messageboard_private_topic

  get '/:messageboard_id/:topic_id(.:format)' => 'posts#index', as: :messageboard_topic_posts
  get '/:messageboard_id/:topic_id/posts(.:format)' => 'posts#index'
  get '/:messageboard_id/:topic_id/:post_id(.:format)' => 'posts#show', as: :messageboard_topic_post
  get '/:messageboard_id/:topic_id/:post_id/edit(.:format)' => 'posts#edit', as: :edit_messageboard_topic_post
  put '/:messageboard_id/:topic_id/:post_id(.:format)' => 'posts#update'
  post '/:messageboard_id/:topic_id/posts(.:format)' => 'posts#create', as: :create_messageboard_topic_post

  resources :messageboards do
    resources :topics do
      resources :posts
    end
  end

  root to: 'messageboards#index'
end

app/controllers/setups_controller.rb
class SetupsController < ApplicationController
  layout 'setup'
  helper_method :step, :setting_up

  def new
    if not_on_correct_step
      redirect_to correct_step
    end

    case step
      when '1'
        @user = User.new
      when '2'
        @app_config = AppConfig.new
      when '3'
        @messageboard = Messageboard.new
    end
  end

  def create
    case step
    when '1'
      @user = User.create(params[:user])
      @user.superadmin = 1
      @user.save

      if @user.valid?
        redirect_to '/2'
      else
        flash[:error] = 'There were errors creating your user.'
        render action: :new
      end
    when '2'
      @user = User.last
      @app_config = AppConfig.create(params[:app_config])
      redirect_to '/3' if @app_config.valid?
    when '3'
      @user = User.last
      @site = AppConfig.first
      messageboard_params = params[:messageboard]
      @messageboard = Messageboard.create(messageboard_params)

      if @messageboard.valid?
        @user.admin_of @messageboard
        @messageboard.topics.create(
          user: @user,
          last_user: @user,
          title: "Welcome to your messageboard's very first thread",
          posts_attributes: {
            '0' => {
              content: "There's not a whole lot here for now.",
              user: @user,
              ip: '127.0.0.1',
              messageboard: @messageboard
            }
          }
        )

        sign_in @user
        redirect_to root_path
      end
    end
  end

  private

  def not_on_correct_step
    step == '1' && User.any? ||
      step == '2' && (AppConfig.any? || User.scoped.empty?) ||
      step == '3' && (Messageboard.any? || AppConfig.scoped.empty? || User.scoped.empty?)
  end

  def correct_step
    if User.any? && AppConfig.any? && Messageboard.scoped.empty?
      '/3'
    elsif User.any? && AppConfig.scoped.empty?
      '/2'
    elsif User.scoped.empty?
      '/1'
    end
  end

  def step
    @step ||= params[:step] || '1'
  end

  def setting_up
    case step
      when '1'
        @setting_up = 'User'
      when '2'
        @setting_up = 'App Configuration'
      when '3'
        @setting_up = 'Messageboard'
    end
  end
end

app/views/setups/_new_1.html.erb
<%= form_for(@user, as: :user, url: create_setup_path(step: step || '1'), method: :post) do |f| %>
  <div id="setup-container">
    <p class="setup-overview-text">
      It is easy to get started with thredded.
      By following these simple steps you will be on your way to creating
      your own community.
    </p>

    <dl>
      <dt><%= f.label :name, 'Username' %></dt>
      <dd><%= f.text_field :name %></dd>

      <dt><%= f.label :email %></dt>
      <dd><%= f.text_field :email %></dd>

      <dt><%= f.label :password %></dt>
      <dd><%= f.password_field :password %></dd>

      <dt><%= f.label :password_confirmation %></dt>
      <dd><%= f.password_field :password_confirmation %></dd>
    </dl>

    <%= f.submit 'Continue', :class => 'btn setup-continue-btn' %>
  </div>
<% end %>

app/views/setups/_new_2.html.erb
<%= form_for(@app_config, as: :app_config, url: create_setup_path(step: step || '2'), method: :post) do |f| %>
  <div id="setup-container">
    <p class="setup-overview-text">
      Below are the global configuration options for your messageboard.
      These can be altered at a later date by visiting the administration
      section of your thredded messageboard.
    </p>

    <dl>
      <dt><%= f.label :title %></dt>
      <dd><%= f.text_field :title %></dd>

      <dt><%= f.label :description %></dt>
      <dd><%= f.text_field :description %></dd>

      <dt><%= f.label :email_from, 'Emails from this site will come from' %></dt>
      <dd><%= f.text_field :email_from %>
        <br>
        <p class="setup-explanation-text">
          This is the "no reply" email address you would like to have as your
          "reply-to" address.
        </p>
      </dd>

      <dt><%= f.label :email_subject_prefix %></dt>
      <dd><%= f.text_field :email_subject_prefix %>
        <br>
        <p class="setup-explanation-text">
          This will prepend email subjects from your site. Eg: <em>"[Thredded]
          You have been sent a new private topic"</em>
        </p>
      </dd>

      <dt><%= f.label :incoming_email_host %></dt>
      <dd><%= f.text_field :incoming_email_host %>
        <br>
        <p class="setup-explanation-text">
          This incoming email host is the hostname you set at your email relay
          provider. Eg: <em>reply.yourwebsite.com</em>
        </p>
      </dd>
    </dl>

    <%= f.submit 'Continue', class: 'btn setup-continue-btn' %>
  </div>
<% end %>

app/views/setups/_new_3.html.erb
<%= form_for(@messageboard, as: :messageboard, url: create_setup_path(step: step || '3'), method: :post) do |f| %>
  <div id="setup-container">
    <p class="setup-overview-text">
      These will be the settings and permissions for your first thredded
      messageboard.
    </p>

    <dl>
      <dt><%= f.label :title %></dt>
      <dd><%= f.text_field :title %></dd>

      <dt><%= f.label :name, 'URL Slug' %></dt>
      <dd>
        <%= f.text_field :name %>
        <br>
        <p class="setup-explanation-text">
          A friendly and easy to remember URL for your messageboard
          (alphanumeric characters only).
        </p>
      </dd>


      <dt><%= f.label :description %></dt>
      <dd><%= f.text_field :description %></dd>

      <dt><%= f.label :security %></dt>
      <dd>
        <%= f.select :security, [:private, :public, :logged_in] %>
        <br>
        <p class="setup-explanation-text">
          This will set the visibility of your messageboard to the public
          members.
        </p>
      </dd>


      <dt><%= f.label :posting_permission %></dt>
      <dd>
        <%= f.select :posting_permission, [:members, :logged_in, :anonymous] %>
        <br>
        <p class="setup-explanation-text">
          The required minimum permissions to post in your messageboard.
        </p>
      </dd>
    </dl>

    <%= f.submit 'Continue', class: 'btn setup-continue-btn' %>
  </div>
<% end %>

app/views/setups/new.html.erb
<% content_for :page_title do %>Thredded Setup &raquo; <%= setting_up %><% end %>

<h1>Setup &raquo; <%= setting_up %></h1>

<%= render "new_#{step}" %>