config/routes.rb
Thredded::Application.routes.draw do
  mount_sextant if Rails.env.development?
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  resources :users

  devise_scope :user do
    match '/auth/:provider/callback', to: 'sessions#create'
  end

  get '/auth/failure', to: redirect('/')
  get '/auth/github', as: :auth_github
  put '/identities' => 'identities#update', as: :identity
  post '/mail/receive' => 'griddler/emails#create'

  constraints(SetupThredded.new) do
    root to: 'setups#new'
    get '/:step' => 'setups#new', constraints: { step: /\d{1}/ }, as: :new_setup
    post '/:step' => 'setups#create', constraints: { step: /\d{1}/ }, as: :create_setup
    resource :setup
  end

  resources :preferences

  match '/login' => redirect('/users/sign_in')
  match '/log_in' => redirect('/users/sign_in')
  match '/sign_in' => redirect('/users/sign_in')
  match '/logout' => redirect('/users/sign_out')
  match '/log_out' => redirect('/users/sign_out')
  match '/forgot_password' => redirect('/users/password/new')
  match '/user/forgot_password' => redirect('/users/password/new')
  match '/user/forgot_username' => redirect('/users/password/new')

  constraints(lambda{|req| req.env["QUERY_STRING"].include? 'q=' }) do
    get '/:messageboard_id(.:format)' => 'topics#search', as: :messageboard_search
  end

  get '/:messageboard_id/users' => 'users#index', as: :messageboard_users

  get '/:messageboard_id(.:format)' => 'topics#index', as: :messageboard_topics
  get '/:messageboard_id/topics/new/(:type)' => 'topics#new', as: :new_messageboard_topic
  get '/:messageboard_id/topics/category/:category_id' => 'topics#by_category', as: :messageboard_topics_by_category
  get '/:messageboard_id/:topic_id/edit(.:format)' => 'topics#edit', as: :edit_messageboard_topic
  put '/:messageboard_id/:topic_id(.:format)' => 'topics#update', as: :messageboard_topic
  post '/:messageboard_id/topics(.:format)' => 'topics#create', as: :create_messageboard_topic

  get '/:messageboard_id/private_topics/new/(:type)' => 'private_topics#new', as: :new_messageboard_private_topic
  get '/:messageboard_id/private_topics(.:format)' => 'private_topics#index', as: :messageboard_private_topics
  post '/:messageboard_id/private_topics(.:format)' => 'private_topics#create', as: :create_messageboard_private_topic

  get '/:messageboard_id/:topic_id(.:format)' => 'posts#index', as: :messageboard_topic_posts
  get '/:messageboard_id/:topic_id/posts(.:format)' => 'posts#index'
  get '/:messageboard_id/:topic_id/:post_id(.:format)' => 'posts#show', as: :messageboard_topic_post
  get '/:messageboard_id/:topic_id/:post_id/edit(.:format)' => 'posts#edit', as: :edit_messageboard_topic_post
  put '/:messageboard_id/:topic_id/:post_id(.:format)' => 'posts#update'
  post '/:messageboard_id/:topic_id/posts(.:format)' => 'posts#create', as: :create_messageboard_topic_post

  resources :messageboards do
    resources :topics do
      resources :posts
    end
  end

  root to: 'messageboards#index'
end

app/views/shared/_currently_online.html.erb
<% if messageboard %>
  <% cache(["currently_online", messageboard.id], expires_in: 1.minute) do %>
    <div class="online">
      <h3>Currently Online</h3>
      <ul>
        <% User.recently_active_in(messageboard).each do |u| %>
         <li><%= u.name %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/shared/_error_msgs.html.erb
		<% [:info, :error, :notice, :alert, :warning].each do |key| %>
			<% if flash[key] %>
				<div class="<%= key %>" id="flash">
					<%= flash[key] %>
				</div>
			<% end %>
		<% end %>

app/views/shared/_google_analytics.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= ENV['GOOGLE_ANALYTICS_ID'] %>']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/shared/_topic_nav.html.erb
<div class="topic_nav">
  <% if can? :create, messageboard.topics.build %>
    <ul class="actions">
      <li class='new_topic'><%= link_to 'new topic', new_messageboard_topic_path(messageboard) %></li>
      <li class='new_private_topic'><%= link_to 'private topic', new_messageboard_private_topic_path(messageboard) %></li>
    </ul>
  <% end %>

  <ul class="listings">
    <li class="topic_list"><%= link_to 'topics', messageboard_topics_path %></li>

    <% if can? :list, messageboard.private_topics.build %>
      <li class="private_topic_list"><%= link_to 'private topics', messageboard_private_topics_path %></li>
    <% end %>

    <%= render 'search/form' %>
  </ul>
</div>