config/routes.rb
Thredded::Application.routes.draw do
  mount_sextant if Rails.env.development?
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  resources :users

  devise_scope :user do
    match '/auth/:provider/callback', to: 'sessions#create'
  end

  get '/auth/failure', to: redirect('/')
  get '/auth/github', as: :auth_github
  put '/identities' => 'identities#update', as: :identity
  post '/mail/receive' => 'griddler/emails#create'

  constraints(SetupThredded.new) do
    root to: 'setups#new'
    get '/:step' => 'setups#new', constraints: { step: /\d{1}/ }, as: :new_setup
    post '/:step' => 'setups#create', constraints: { step: /\d{1}/ }, as: :create_setup
    resource :setup
  end

  resources :preferences

  match '/login' => redirect('/users/sign_in')
  match '/log_in' => redirect('/users/sign_in')
  match '/sign_in' => redirect('/users/sign_in')
  match '/logout' => redirect('/users/sign_out')
  match '/log_out' => redirect('/users/sign_out')
  match '/forgot_password' => redirect('/users/password/new')
  match '/user/forgot_password' => redirect('/users/password/new')
  match '/user/forgot_username' => redirect('/users/password/new')

  constraints(lambda{|req| req.env["QUERY_STRING"].include? 'q=' }) do
    get '/:messageboard_id(.:format)' => 'topics#search', as: :messageboard_search
  end

  get '/:messageboard_id/users' => 'users#index', as: :messageboard_users

  get '/:messageboard_id(.:format)' => 'topics#index', as: :messageboard_topics
  get '/:messageboard_id/topics/new/(:type)' => 'topics#new', as: :new_messageboard_topic
  get '/:messageboard_id/topics/category/:category_id' => 'topics#by_category', as: :messageboard_topics_by_category
  get '/:messageboard_id/:topic_id/edit(.:format)' => 'topics#edit', as: :edit_messageboard_topic
  put '/:messageboard_id/:topic_id(.:format)' => 'topics#update', as: :messageboard_topic
  post '/:messageboard_id/topics(.:format)' => 'topics#create', as: :create_messageboard_topic

  get '/:messageboard_id/private_topics/new/(:type)' => 'private_topics#new', as: :new_messageboard_private_topic
  get '/:messageboard_id/private_topics(.:format)' => 'private_topics#index', as: :messageboard_private_topics
  post '/:messageboard_id/private_topics(.:format)' => 'private_topics#create', as: :create_messageboard_private_topic

  get '/:messageboard_id/:topic_id(.:format)' => 'posts#index', as: :messageboard_topic_posts
  get '/:messageboard_id/:topic_id/posts(.:format)' => 'posts#index'
  get '/:messageboard_id/:topic_id/:post_id(.:format)' => 'posts#show', as: :messageboard_topic_post
  get '/:messageboard_id/:topic_id/:post_id/edit(.:format)' => 'posts#edit', as: :edit_messageboard_topic_post
  put '/:messageboard_id/:topic_id/:post_id(.:format)' => 'posts#update'
  post '/:messageboard_id/:topic_id/posts(.:format)' => 'posts#create', as: :create_messageboard_topic_post

  resources :messageboards do
    resources :topics do
      resources :posts
    end
  end

  root to: 'messageboards#index'
end

app/models/post.rb
class Post  < ActiveRecord::Base
  require 'gravtastic'
  include Gravtastic
  gravtastic :user_email

  include BaseFilter
  include TextileFilter
  include BbcodeFilter
  include MarkdownFilter
  include AttachmentFilter
  include EmojiFilter
  include AtNotificationFilter

  paginates_per 50

  attr_accessible :attachments_attributes,
    :content,
    :filter,
    :ip,
    :messageboard,
    :source,
    :topic,
    :user

  cattr_accessor(:notification_enabled) { true }

  default_scope order: 'id ASC'
  belongs_to :messageboard, counter_cache: true, touch: true
  belongs_to :topic, counter_cache: true
  belongs_to :user, counter_cache: true, touch: true
  has_many   :attachments
  has_many   :post_notifications

  accepts_nested_attributes_for :attachments

  validates :content, presence: true
  validates :messageboard_id, presence: true
  validates :user_id, presence: true

  def create
    super &&
      modify_parent_topic
  end

  def create_or_update
    set_user_email &&
      super &&
      notify_at_users
  end

  private

  def modify_parent_topic
    topic.last_user = user
    topic.touch
    topic.save
  end

  def set_user_email
    self.user_email = user.email
  end

  def notify_at_users
    if self.notification_enabled
      AtNotifier.new(self).notifications_for_at_users
    else
      true
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include TopicsHelper
  load_and_authorize_resource only: [:index, :show]

  before_filter :ensure_topic_exists
  before_filter :pad_post, only: :create
  helper_method :messageboard, :topic
  layout 'application'

  def index
    authorize! :read, topic

    @post = Post.new(
      topic: topic,
      messageboard: messageboard,
      filter: current_user.try(:post_filter)
    )

    @posts = topic
      .posts
      .includes(user: :roles)
      .page(page)

    @read_status = UserTopicRead.find_or_create_by_user_and_topic(current_user, topic, page)

    if not_inside_topic_and_in_an_old_page?
      redirect_to_later_page
    else
      UserTopicRead.update_read_status!(current_user, topic, page)
    end
  end

  def create
    p = topic.posts.create(params[:post])
    redirect_to :back
  end

  def edit
    authorize! :edit, post
  end

  def update
    authorize! :update, post
    post.update_attributes(params[:post])
    redirect_to messageboard_topic_posts_path(messageboard, topic)
  end

  private

  def post
    post = topic.posts.find(params[:post_id])
    @post ||= post
  end

  def not_inside_topic_and_in_an_old_page?
    !internal_to_topic? && page == 1 && @read_status.page > 1
  end

  def page
    params[:page].nil? ? 1 : params[:page].to_i
  end

  def extra_data
    %Q{data-latest-read=#{@read_status.post_id || 0}} if @read_status
  end

  def internal_to_topic?
    referer = request.referer || ''
    referer.include?("#{topic.id}?page=") || (!topic.slug.nil? && referer.include?("#{topic.slug}?page="))
  end

  def redirect_to_later_page
    redirect_to messageboard_topic_posts_path(messageboard, topic, page: @read_status.page)
  end

  def pad_post
    params[:post][:ip] = request.remote_ip
    params[:post][:user] = current_user
    params[:post][:messageboard] = messageboard
  end

  def ensure_topic_exists
    if topic.blank?
      redirect_to default_home,
        flash: { error: 'This topic does not exist.' }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def link_to_edit_post(site, messageboard, topic, post)
    path = edit_messageboard_topic_post_path(messageboard.name, topic, post)
  end
end

app/views/posts/_form.html.erb
  <li class="content">
    <%= f.label :content %>
    <%= f.text_area :content, { rows: 5, tabindex: 3 }  %>
  </li>

  <%= f.fields_for :attachments do |attachment_form|  %>
    <li class="attachment"> 
      <%= attachment_form.file_field :attachment %>
      <%= attachment_form.link_to_remove 'Remove this attachment',
        { class: 'remove_attachment' } %>
    </li>
  <% end -%>

  <li>
    <%= f.link_to_add 'Add an attachment', :attachments,
      { class: 'add_attachment', tabindex: 5 }%>
  </li>
  <li>
    <%= f.select :filter, Post::Filters, {}, tabindex: 4 %>
    <a href="#pseudo-help" title="huh?" class="hide-for-small filter-help" id="filter-help">?</a>
  </li>

app/views/posts/_login_form.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name),
  html: { class: 'session_mgmt' }) do |f| %>
  <input name="after_sign_in_redirect" type="hidden" value="<%= request.fullpath %>" />

  <h3>
    Sign in below to respond.
  </h3>
  <ul>
    <li>
      <%= f.email_field :email, autocapitalize: 'off',
        autocorrect: 'off', autofocus: 'autofocus', placeholder: 'Email' %>
    </li>

    <li>
      <%= f.password_field :password, placeholder: 'Password' %>
    </li>

    <% if devise_mapping.rememberable? %>
      <li>
        <%= f.label :remember_me do %>
          <%= f.check_box :remember_me %>
          Remember me
        <% end %>
      </li>
    <% end %>

    <li class="submit">
      <%= f.submit 'Sign in' %>
      <%= link_to 'Sign in with Github', auth_github_path(origin: request.fullpath), class: 'provider github' %>
    </li>
    <li>
      <%= link_to 'Sign up for an account', new_user_registration_path %>
    </li>
  </ul>
<% end %>

app/views/posts/_post.html.erb
<% post = PostDecorator.new(post) %>

<%= content_tag_for(:article, post) do %>
  <% cache post do %>
    <header>
      <%= image_tag post.gravatar_url, class: 'avatar' %>
      <cite>
        <%= link_to post.user_name, post.user %>
        <%= post.created_at_timeago %>
      </cite>
    </header>

    <div class="content">
      <p><%= post.filtered_content %></p>
      <ul class="attachments"><%= render post.attachments %></ul>
    </div>
  <% end %>

  <footer>
    <% if can? :edit, post.original %>
      <%= link_to 'edit post',
        edit_messageboard_topic_post_path(messageboard, topic, post),
        class: 'edit' %>
    <% end %>
  </footer>
<% end %>

app/views/posts/edit.html.erb
<% content_for :page_id do %>posts_edit<% end %>
<% content_for :page_title do %>
  <%= app_config.title %> | <%= messageboard.title %> | Edit Post
<% end %>

<header>
  <nav>
    <ul class="breadcrumbs">
      <li><a href="/">Forums</a></li>
      <li><%= link_to messageboard.title,
        messageboard_topic_posts_path(messageboard, topic) %></li>
      <li>
        <span>
          Editing Post - <%= link_to "##{@post.id}",
          messageboard_topic_posts_path(messageboard, topic) + "#post_#{@post.id}" %>
        </span>
      </li>
    </ul>
  </nav>
</header>

<div class="forms">
  <%= nested_form_for([messageboard, topic, @post], url: { action: 'update' },
    html: { method: :put, class: :topic_form }) do |f| %>
    <ul>
      <%= render 'form', f: f %>
      <li class="submit">
        <%= f.submit 'Update Post', { tabindex: 2 } %>
      </li>
    </ul>
  <% end %>
</div>

app/views/posts/index.html.erb
<% content_for :page_id do %>topics_posts<% end %>
<% content_for :page_title do %>
  <%= app_config.title %> | <%= topic.title %> | Posts
<% end %>

<header>
  <nav>
    <ul class="breadcrumbs">
      <li><%= link_to 'Forums', root_path %></li>
      <li><%= link_to messageboard.title, messageboard_topics_path(messageboard) %></li>
      <li>
        <span>
          <%= topic.title %>

          <% if can? :edit, topic %>
            <%= link_to 'edit', edit_messageboard_topic_path(messageboard, topic) %>
          <% end %>
        </span>
      </li>
    </ul>
  </nav>

  <% if topic.users_to_sentence.present? %>
    <cite><%= topic.users_to_sentence %></cite>
  <% end %>

  <%= render 'shared/currently_online' %>
  <%= render 'shared/topic_nav' %>
</header>

<section class="posts">
  <%= render @posts %>
</section>

<footer>
  <%= paginate @posts %>

  <% if can? :create, @post %>
    <div class="forms">
      <%= nested_form_for([messageboard, topic, @post],
        url: create_messageboard_topic_post_path(messageboard, topic, @post),
        html: { multipart: true }) do |f| %>
        <ul>
          <%= render 'form', f: f %>
          <li class="submit"><%= f.submit 'Submit reply', { tabindex: 3 } %></li>
        </ul>
      <% end %>
    </div>
  <% elsif !signed_in? %>
    <div class="sign_in_to_post">
      <%= render 'login_form', resource: User.new, resource_name: :user %>
    </div>
  <% end %>

  <nav>
    <ul class="breadcrumbs">
      <li><%= link_to 'Forums', root_path %></li>
      <li><%= link_to messageboard.title, messageboard_topics_path(messageboard) %></li>
      <li>
        <span>
          <%= topic.title %>

          <% if can? :edit, topic %>
            <%= link_to 'edit', edit_messageboard_topic_path(messageboard, topic) %>
          <% end %>
        </span>
      </li>
    </ul>
  </nav>
</footer>